### ISSUE TITLE
Node not working in dockerized Node-Red

### ISSUE THREAD

**Issue by merlinschumacher** [mattdavis90/node-red-contrib-tado-client#1]
Hi,

i use Node-Red in a Docker-Container on a Raspberry Pi. Installing this node fails with the following error in the log:
```
21 Nov 22:07:03 - [info] Installing module: node-red-contrib-tado-client, version: 0.1.6
21 Nov 22:07:20 - [info] Installed module: node-red-contrib-tado-client
21 Nov 22:07:20 - [info] Added node types:
21 Nov 22:07:20 - [info]  - node-red-contrib-tado-client:tado-config : SyntaxError: Unexpected token function
21 Nov 22:07:20 - [info]  - node-red-contrib-tado-client:tado : SyntaxError: Unexpected token function
21 Nov 22:09:58 - [warn] Credential type 'tado-config' is not registered
21 Nov 22:09:58 - [info] Stopping flows
```

**Comment by mattdavis90** [comment]
Hi,
I also run node-red in a docker container. I run on x86 though not a Raspberry Pi, though I'm not sure that will make a difference. Do you know which version of the docker image you are running? I'll grab a clean image and see if I can replicate the issue. Also, did you install via the plugin via the WebUI?
Thanks

**Comment by merlinschumacher** [comment]
I tried it on x86 as well, because I suspected the same, but it still happens. 
I use `nodered/node-red-docker:rpi` on the Pi in the latest version. I just rebuild the container.
I installed the plugin via the palette in the webui.
These are the error messages / visual errors i see in the webui:
![screenshot_2018-11-27 node-red mother 2](https://user-images.githubusercontent.com/7475989/49091540-5adcc480-f260-11e8-89c9-a3751e4f8be6.png)
![screenshot_2018-11-27 node-red mother](https://user-images.githubusercontent.com/7475989/49091544-5ca68800-f260-11e8-8d20-a3b076de25ea.png)

**Comment by mattdavis90** [comment]
Hi, I've just tested this myself and it looks like async functions weren't introduced into node.js until around v7 and the default node-red containers use v6. If you switch to the nodered/node-red-docker:rpi-v8 image then hopefully this plugin will work for you. Thanks

**Comment by merlinschumacher** [comment]
This fixed it! Thank you for your assistance!

**Comment by Harald-U** [comment]
Hi @mattdavis90 
FYI: this issue seems to be back. I updated the node-red-contrib-tado-client from the Node-RED dashboard yesterday and after that I got the "Flows stopped due to missing node types: tado-config, tado"
I am running dockerized Node-Red, based on `image: nodered/node-red:latest`. This is still based on node.js version 10.
My solution was to build a custom Node-Red image based on node.js V12 following the instruction here https://github.com/node-red/node-red-docker/tree/master/docker-custom 
Don't know if it was really the node version but at least it fixed the issue.
This may be a problem when running on a Raspi, the docker build could take quite some time.

**Comment by mattdavis90** [comment]
Hi Harold, thanks for getting in touch. Is it possible to try using the latest-12 tag to see if that rectifies the issue. This is the image that I run and shouldn't require a custom build.

**Comment by Harald-U** [comment]
@mattdavis90  Perfect, using :latest-12 works! I should have checked Dockerhub :-/
Thanks a lot, for your help and the tado-client, and have a good weekend!

**Comment by mattdavis90** [comment]
Glad that's working. No problem, and have a good weekend as well
