### ISSUE TITLE
Zone offset function

### ISSUE THREAD

**Issue by robons17** [mattdavis90/node-red-contrib-tado-client#10]
Is it possibile to add the possibility to set temperature offset? I woud to set it by reading an external sensor to adjust the tvr value

**Comment by uuzi** [comment]
That indeed would be great! I've found the temperature readings of the radiator thermostats is quite unreliable, so having a external temperature sensor that would be more accurate that i could use to calculate the correct offset values would be just awesome!

**Comment by mattdavis90** [comment]
Sorry for taking the time to reply. I don't own a thermostatic radiator valve to do the testing. How would you envisage this working? The target temperature can be set both on the node and injected as a message, so if you were to read a value from an external source pass through a function block to add a value to the reading, then through some logic to determine on/off state, then finally into the tado node to set the zone control to manual; does that work, or did I misunderstand? Thanks

**Comment by robons17** [comment]
I have in mind to read temperature external sensor and valve. Calculate difference and update the offset value (delta beetween new offset and old offset).
In a comment i read that api would be



There are some extra endpoints that some might find usefull:
Temperature offset

PUT https://my.tado.com/api/v2/devices/<device-serial-id>/temperatureOffset

it accepts the following payload:

{
            celcius: 0.2
}
(also fahrenheit). and will return the offset in both formats.


Thanks

**Comment by robons17** [comment]
Sorry i m from mobile api

PUT https://my.tado.com/api/v2/devices/<device-serial-id>/temperatureOffset

**Comment by uuzi** [comment]
so if i'm understanding robons17 correctly, the only thing that would need to be added to your tado client is to read the current offset value and to accept a message containing the desired offset value and set that value in the thermostat via the API.

everything else, namely the calculation of the correct offset value can be done with node red outside of the tado client

**Comment by robons17** [comment]
This is my idea. I think it can work...and i hope we can fix the reading of valves....

**Comment by robons17** [comment]
@mattdavis90 
i try to edit your code. now i'm able to read offset value.
Next Step, is to try to insert the put method.

    gettemperatureOffset(device_id) {
        return this.apiCall(`/api/v2/devices/${device_id}/temperatureOffset`);
    }

**Comment by mattdavis90** [comment]
I've added the functionality that you requested into the underlying library and into this node-red module. Apologies for the delay on implementing this. If you update to v0.3.0 you should now be able to set and read the temperatureOffset.

**Comment by robons17** [comment]
Thanks a lot

Il gio 28 nov 2019, 22:14 Matt Davis <notifications@github.com> ha scritto:

**Comment by robons17** [comment]
I ll try to update saturday. Cause now i do not see the .js modified. (Sorry i m on mobile)

**Comment by robons17** [comment]
i have installed v 0.3.0 but it does not work. i think tado.js of node-red-contrib-tado-client must be update. i'll try....

**Comment by robons17** [comment]
I have edit some files on both packages and now new functions seem to work.
if you give me an email address i'll send you all files so yuo can check my modification.
Rubens

**Comment by mattdavis90** [comment]
Hi Rubens,

Apologies for that. It serves me right for trying to push out the update without putting the time aside to do the work and test it. I've update the JS file now as required and published v0.3.1 of the library. Hopefully this will work for you. My sincerest apologies that this has taken so long.

The getDeviceTemperatureOffset method works and returns both celsius and farenheit. The setDeviceTemperatureOffset currently only accepts the temperature in celsius, as with my other calls and expects the value to be in msg.temperature (not msg.payload.temperature).

Thanks

**Comment by robons17** [comment]
Hi matt, i work also in html file, for fix the offset settings from gui. I
ll see your code later

Il dom 1 dic 2019, 14:37 Matt Davis <notifications@github.com> ha scritto:

**Comment by mattdavis90** [comment]
Hi Rubens, If you have your changes available as a PR then I'm happy to get
them merged. Thanks

**Comment by robons17** [comment]
I open  my laptop and i try

**Comment by robons17** [comment]
please let me konw if you view the files.

**Comment by mattdavis90** [comment]
Not got my laptop with me at the minute but had a look at your changes. I'll get these rolled into v0.3.2 tomorrow morning. Thanks

**Comment by uuzi** [comment]
@robons17 : I've had very little time in the last few weeks and don't we that changing anytime soon. Holidays and all... Could you tell me how you implemented the offset function in your automation?

**Comment by mattdavis90** [comment]
Sorry that I have only just got around to fixing this - life has been very busy of late. I've pushed up version 0.4.0 with some additional presence stuff in it from another commit.

**Comment by robons17** [comment]
Sorry uuzi, i m not on laptop.
But u create a sensor which value is sensor_temperature-tado_temperature.
When it change i get offset from tado server, sum with sensor value and update on tado server (only if the two values are different).
It works . The only iussue is tado app notify me several wrong open window event. But i try to fix, calculating trend of my sensor...

**Comment by mattdavis90** [comment]
Hi, how did you get on with v0.4.0? Are you happy for me to close this issue? Thanks

**Comment by robons17** [comment]
Hi matt, it is working. Now i'm using 0.4.0 (not sure if i made some changes but i think it is working as is). We can ask  @uuzi beforr close iussue. If we have no response i close it tomorow. Thanks

**Comment by uuzi** [comment]
Issue can be closed. Works as expected.
It seems to disconnect the gateway from the Tado servers if you abuse it,
e.g. by checking every few seconds and writing new offsets accordingly but
that would be a user implementation problem that could be mentioned in
documentation.

**Comment by chima2g** [comment]
The valve motor operates every time an offset is put. This opens the radiator full blast. Even though it’s only for a second, it can significantly increase the temperature of the room. If you're periodically setting the offset, the resultant increase to the room temperature renders this feature counter productive at best (or at least for me it does). Please vote [here](https://community.tado.com/en-gb/discussion/4325/disable-trv-calibration-when-offset-is-changed-required-for-using-external-sensor) for tado to stop the operating of the motor upon setting the offset so we can take full advantage of this feature... Pretty please with a cherry on top
