### ISSUE TITLE
Unable to set Presence

### ISSUE THREAD

**Issue by petexa** [mattdavis90/node-red-contrib-tado-client#12]
I am unable to set presence receiving the following message in the debug node.
"Error: Request failed with status code 422"

All other API calls appear to be working.

**Comment by mtjoernelund** [comment]
Just installed and I seem to have the same issue. Did this ever get resolved?

**Comment by kamelohr** [comment]
I'm bothered by the same issue. Seems like it's not the client's fault but the API's. According to this German article (https://wirres.net/article/articleview/11348/1/6/) the API only allows you to set the home presence to AWAY when every assigned device of every user is out of the geo fence. But if you try to disable geo fancing on every device the system forces you to stay in the HOME presence mode and declines the presence change to AWAY as well with a 422. Also accoring to https://community.tado.com/en-gb/discussion/549/manual-control-of-home-and-away-mode it's the most requested feature by the community. So, hopefully tado will get it's s**t together and they will release that hilarious API restriction.

**Comment by mattdavis90** [comment]
Apologies I've been away from my computer for Christmas and just getting back into the swing of things.

Thanks for replying to the topic. This aligns with my own experience of the "feature" as well. I have tried taking my phone away from home and can get the API to respond, however as you say forcing off the geo fencing function still responds with 422.

**Comment by mattdavis90** [comment]
Looks like Tado added support for this in the latest version. I've released v0.6.2 of the node-tado-client library and v0.5.1 of this module to support the new endpoint.
