### ISSUE TITLE
Hot water control

### ISSUE THREAD

**Issue by ssypchenko** [mattdavis90/node-red-contrib-tado-client#13]
Hi, 

Would you please add hot water control to the node? 

This is the example how to switch it on
curl -X PUT "https://my.tado.com/api/v2/homes/<home id>/zones/<zone id>/overlay" -H "Authorization: Bearer tadotoken" -H "Content-Type:application/json;charset=UTF-8" --data '{"setting":{"type":"HOT_WATER","power":"ON"},"termination":{"type":"MANUAL"}}'

**Comment by ssypchenko** [comment]
Hi, I managed to modify your code to allow hot water control. I manually add it to my node-red setup. It works perfectly. All other functionality is intact. 
I'm not used to working with git-hub, unfortunately. This is the link to a DropBox folder with modified files. 
https://www.dropbox.com/sh/gnsanr0uj25jw7p/AACE4AoQ3qwWR6fsw_NkuqaNa?dl=0
If you want I can make Russian translation of locales :) 

Would you please check and upload to your code to make it official?

Thanks
Sergey

**Comment by csmale** [comment]
Hi @ssypchenko , thanks very much for this modification - it does just what I need! I was about to change this myself, but you beat me to it!

@mattdavis90 could this be picked up and merged please?

**Comment by csmale** [comment]
I was wondering... could the heat type (HEATING or HOT_WATER) not be found automatically from the zone data?

**Comment by mattdavis90** [comment]
This addition is no in node-tado-client v0.6.1
I impleted the suggestion by @csmale by pulling the type of the zone before writing to it. THis should allow you to be able to overwrite a HOT_WATER zone. I don't think anything need changing on the nodered side as this just uses the already available "setZoneOverlay" call. The call will ignore Temperature for non-HEATING zones.

**Comment by mattdavis90** [comment]
This is now available in v0.5.0

**Comment by mattdavis90** [comment]
@ssypchenko @csmale Could either of you confirm that this functionality is now working? Thanks

**Comment by csmale** [comment]
Hi Matt, yes, it seems to be working fine. Thanks for your effort on this.
