### ISSUE TITLE
Feature request: Turn on/off mobile device Geo

### ISSUE THREAD

**Issue by derekoharrow** [mattdavis90/node-red-contrib-tado-client#16]
Love the Tado client - works great.

Can you add the ability to turn on/off geo-location for mobile devices.

You can do this using the API call _/api/v2/homes/<homeID>/mobileDevices/<deviceID>/settings_ with a value of

```
{
  "geoTrackingEnabled": true
}
```

If not, it would be useful to be able to get to the Tado authorisation token so that you can use this directly in HTTP calls.

Thanks

**Comment by mattdavis90** [comment]
Hi, sorry for the delay. I've just been playing around with this and I'll add the functionality along with a couple of other bits into the node-tado-client repo then add the functionality to the nodered client as well. This should be done in the next couple of hours. Again, sorry for the delay :)

**Comment by mattdavis90** [comment]
This is now available in v0.5.0

**Comment by derekoharrow** [comment]
That's brilliant, thank-you! I'll give it a try.
And no need to apologise for any delay.
