### ISSUE TITLE
Get air comfort

### ISSUE THREAD

**Issue by AcHoBi** [mattdavis90/node-red-contrib-tado-client#17]
I'm missing the 'Get air comfort' function. It worked great in version 0.4.
Any idea what happened?

**Comment by mattdavis90** [comment]
Hi @AcHoBi,
Apologies for the inconvenience.
I didn't remove anything in the latest release but I did chase some bits and pieces in the underlying library. Do you know exactly what calls you were making? I don't have an A/C unit to test air comfort with.
Thanks

**Comment by mattdavis90** [comment]
Hi @AcHoBi do you have an update on your issue? Thanks
