### ISSUE TITLE
Activate open window

### ISSUE THREAD

**Issue by martyn82** [mattdavis90/node-red-contrib-tado-client#19]
Hi @mattdavis90 , I am using your library with great fun and success! Thanks for that!

I was wondering if it would be possible to add the 'activate open window' feature?
It seems it's just another API call. I assume it could work just like you would enable it manually through the Tado app.

Thanks in advance!

**Comment by mattdavis90** [comment]
Hi @martyn82 I'll have a look on the web interface later to find the API call and update the library. Thanks

**Comment by mattdavis90** [comment]
I've added the window detection code into the underlying library and have also added this functionality in v0.6.0 of this node-red module. Hopefully this is to your liking.

The new functionality allows setting the WindowDetection. To read the state, this is already possible in the getZones API call.

**Comment by martyn82** [comment]
Thanks! I'll check it out ASAP.

**Comment by martyn82** [comment]
Works great!

I noticed that there's also a possibility to actually activate the openwindow mode on a zone, when an open window was detected in that zone (with `openWindow: true` in the state of the zone). Which is something I would definitely use to automate (saves subscription costs :-) ).

It's possible with:
`POST /api/v2/homes/${home_id}/zones/${zone_id}/state/openWindow/activate`

And cancel with:
`DELETE /api/v2/homes/${home_id}/zones/${zone_id}/state/openWindow`

**Comment by martyn82** [comment]
Hi @mattdavis90 , I made two patches for this functionality to work. One for the `node-tado-client` repo and one for this repo.

To be able to use this feature, a zone's state should report `"openWindowDetected": true`. Then it is able to activate the open window mode for that zone. And only if that mode is active, it is possible to cancel it.

Please take a look and let me know.

[node-red-contrib-tado-client.patch.txt](https://github.com/mattdavis90/node-red-contrib-tado-client/files/4479549/node-red-contrib-tado-client.patch.txt)
[node-tado-client.patch.txt](https://github.com/mattdavis90/node-red-contrib-tado-client/files/4479551/node-tado-client.patch.txt)

**Comment by Brewj** [comment]
Hi @mattdavis90 and @martyn82 , thank you so much for your development work on this, it's really great. It would be fantastic if there was a node we could poll at intervals and report if there is or is not a open window detected. Or better still report if there was a state change.

**Comment by mattdavis90** [comment]
@martyn82 I'll look at integrating your patches today, thanks.

@Brewj It is actually already possible to determine whether the Tado has detected an open window using the getZoneState call. If you poll this then there is a windowOpen property in the returned JSON.

**Comment by Brewj** [comment]
Ah magic thank you.

**Comment by martyn82** [comment]
@Brewj more specifically, with Node Red you can use the inject node with an interval of, say every 30 secs, to fetch the states of your zones.

If in the zone state there's a `openWindowDetected` property (value = `true`) then you can issue the activate open window mode on that zone.

**Comment by Brewj** [comment]
@martyn82 all over it 
<img width="1200" alt="Screenshot 2020-04-15 at 10 25 47" src="https://user-images.githubusercontent.com/5247403/79321633-8fa7f500-7f03-11ea-8502-39b39626a380.png">

**Comment by mattdavis90** [comment]
Hi @martyn82 I've just published v0.7.0 of the library with your additions

**Comment by martyn82** [comment]
Cool! Thanks a lot!
