### ISSUE TITLE
input payload

### ISSUE THREAD

**Issue by Folgore796** [mattdavis90/node-red-contrib-tado-client#2]
Sorry for the trouble, but I do not understand how to structure the payload to send as input to your node to make setZoneOverlay. (temperature, on / off, etc.)

thanks a lot

**Comment by mattdavis90** [comment]
Hi, I'll be honest setZoneOverlay isn't something I've used in nodered - I've used it as a nodejs library though. Having now had a play around in nodered I can see that it is a bit of a pain to use. The library expects a message like the following;
`{
    "homeId": "12345",
    "zoneId": "1",
    "power": "on",
    "temperature": "15",
    "terminationType": "manual"
}`
The default nodered inject node only has the ability to set msg.payload which isn't compatible with where this node expects the variables to be. As an alternative you can use a function node to set the payload.

Something like this should work. Apologies for the confusion.

`[{"id":"fe31da6e.c76878","type":"tab","label":"Flow 2","disabled":false,"info":""},{"id":"adc19892.4c9598","type":"tado","z":"fe31da6e.c76878","configName":"d1cf260f.0bb368","apiCall":"setZoneOverlay","homeId":"","deviceId":"","zoneId":"","power":"on","temperature":"","terminationType":"manual","terminationTimeout":900,"name":"","x":510,"y":200,"wires":[["842d5f6a.6fe47"]]},{"id":"9bd3b590.abe9b8","type":"inject","z":"fe31da6e.c76878","name":"","topic":"","payload":"{}","payloadType":"json","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":190,"y":200,"wires":[["dba6c40.facfb38"]]},{"id":"842d5f6a.6fe47","type":"debug","z":"fe31da6e.c76878","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","x":680,"y":200,"wires":[]},{"id":"dba6c40.facfb38","type":"function","z":"fe31da6e.c76878","name":"","func":"msg = {\n    \"homeId\": 12345,\n    \"zoneId\": 1,\n    \"power\": \"on\",\n    \"temperature\": 15,\n    \"terminationType\": \"manual\"\n};\nreturn msg;","outputs":1,"noerr":0,"x":330,"y":200,"wires":[["adc19892.4c9598"]]},{"id":"d1cf260f.0bb368","type":"tado-config","z":"","name":""}]`

**Comment by Folgore796** [comment]
Perfect, I have put all json message in msg.payload....not only in msg. I have understand now

Sorry for disturd

**Comment by mattdavis90** [comment]
Not a problem. Glad this is working now
