### ISSUE TITLE
add getState

### ISSUE THREAD

**Issue by dafi87** [mattdavis90/node-red-contrib-tado-client#20]
Hey there,
at first, thanks for all the work you do here! 
Would it be possible to add a call to https://my.tado.com/api/v2/homes/123456/state?
I know you are already using getState internally for updatePresence.

This would be very handy to use as trigger for coming home/ leaving home actions, since the tado presence tracking is always very accurate for me.
I know I could get the same info by looking through all devices, but only looking at getState would make it much easier.

Thanks!

**Comment by mattdavis90** [comment]
Hi @dafi87 I added this functionality into v0.6.0 a couple days ago. Apologies, thought I'd replied. Let me know if this works for you. Thanks

**Comment by dafi87** [comment]
Hey Matt,
thanks for your reply! Unfortunately I actually can't see this being added. A diff of 0.5.0 and 0.6.0 only shows the open window detection being added.
Best,
Daniel

**Comment by mattdavis90** [comment]
Apologies I was looking at the wrong code. I added something else in 0.6.0, got confused and thought you were after getZoneState. I even double check. 100% fail on my part. I'll add the functionality into a new release. Apologies

**Comment by mattdavis90** [comment]
Should be in v0.8.0 now. Again, apologies for the confusion. I'm still not really sure why I didn't add this originally. Thanks for the patience

**Comment by dafi87** [comment]
Hey @mattdavis90 thank you so much for the update! I see it in there now but it's currently only working if you configured the node for a different API call first that needs a Home ID, and so the ID gets stored. You forgot to show the Home ID input if "Get home state" is selected as API call.
Best,
Daniel

**Comment by mattdavis90** [comment]
I knew I'd forgotten something but testing it I couldn't work out what. Sorry, should be fixed in 0.8.1
Thanks
