### ISSUE TITLE
Node stuck in "errored"

### ISSUE THREAD

**Issue by dafi87** [mattdavis90/node-red-contrib-tado-client#23]
From time to time one or multiple of the tado nodes in my flows get stuck in "errored" state. I know, the error itself can have multiple reasons outside the scope of this repo, but the core problem is that the nodes can get stuck in the "errored" state and don't react to input any longer until the flow gets deployed again.
My understanding is, that the nodes shouldn't get stuck but should just error out again while the underlying problem is still there "e.g. tado API unreachable etc.) but would go back to normal when the problem cleared up.

Please let me know if you need any more info.

v0.8.1 on Node-RED 1.1.3

**Comment by mattdavis90** [comment]
I think this may be due to the Oauth token not refreshing. v0.9.0 will be available shortly. Hopefully this will fix your problem. Thanks
