### ISSUE TITLE
Set GeoTracking not working

### ISSUE THREAD

**Issue by derekoharrow** [mattdavis90/node-red-contrib-tado-client#24]
Hi
Using v0.8.1 and trying to turn off/on Geotracking for a mobile device.
When I add the Tado node and select the "Set Geo Tracking for a mobile device" option, I cannot specify which deviceId or homeId in the panel, and no matter what I try I cannot change Geo Tracking from Enabled to Disabled - it just reverts back to Enabled all the time.
Any ideas?
Thanks

**Comment by mattdavis90** [comment]
Thanks for reporting this. Looks like a bug. A fix is in progress and will be in the v0.9.0 release. Thanks

**Comment by derekoharrow** [comment]
Just tried installing v0.9.0 and I just get this in the logs:

```
20 Oct 09:22:29 - [info] Waiting for missing types to be registered:
20 Oct 09:22:29 - [info]  - tado-config
20 Oct 09:22:29 - [info]  - tado
```

And my flows are stopped due to these nodes missing...

**Comment by derekoharrow** [comment]
I also saw this in the Node RED startup log:

```
20 Oct 09:33:00 - [info] Node-RED version: v1.2.2
20 Oct 09:33:00 - [info] Node.js  version: v10.22.1
20 Oct 09:33:00 - [info] Linux 5.0.0-38-generic x64 LE
20 Oct 09:33:01 - [info] Loading palette nodes
20 Oct 09:33:03 - [info] Dashboard version 2.23.4 started at /ui
**20 Oct 09:33:04 - [warn] ------------------------------------------------------
20 Oct 09:33:04 - [warn] [node-red-contrib-tado-client/tado] SyntaxError: Invalid or unexpected token
20 Oct 09:33:04 - [warn] ------------------------------------------------------**
20 Oct 09:33:04 - [info] Settings file  : /data/settings.js
20 Oct 09:33:04 - [info] Context store  : 'default' [module=memory]
20 Oct 09:33:04 - [info] User directory : /data
20 Oct 09:33:04 - [warn] Projects disabled : editorTheme.projects.enabled=false
20 Oct 09:33:04 - [info] Flows file     : /data/flows.json
20 Oct 09:33:04 - [info] Server now running at http://127.0.0.1:1880/
20 Oct 09:33:04 - [warn]
```

**Comment by mattdavis90** [comment]
Hi, I think that is related to the node version you're running. The update to v0.9.0 requires at least node version 12 due to the async function syntax. Are you able to update and see if the issue persists. Apologies for the inconvenience

**Comment by derekoharrow** [comment]
Hmmm. That could be it - thanks.
Just need to figure out how to upgrade it now - I'm running the official node-red docker image (nodered/node-red:latest)

**Comment by derekoharrow** [comment]
Got it! (nodered/node-red:latest-12) - testing now. Thanks!

**Comment by derekoharrow** [comment]
Brilliant - works now! Thank you.
