### ISSUE TITLE
tado-config missing

### ISSUE THREAD

**Issue by romprod** [mattdavis90/node-red-contrib-tado-client#25]
Hi,

I've installed this into Nodered v1.1.3 but I'm missing the tado-config node although it does list it as being installed. I can only use the Tado node as can be seen below.

![image](https://user-images.githubusercontent.com/3393004/96248677-d4d8dc80-0fa3-11eb-87a9-183d2dd03c93.png)

**Comment by mattdavis90** [comment]
Hi @romprod thanks for getting in touch. The tado-config node won't appear with other nodes on the right-hand side. It is accessible once you have added the node to the flow. If you double click on the node then you will see the properties of that node, similar to this
![Screenshot-20201018193004-499x278](https://user-images.githubusercontent.com/4218833/96377052-acefa180-117a-11eb-98c1-15f44062cb8e.png)
Then, if you click on the edit next to config this will create a tado-config node behind the scenes, link it to the current node, and present you with  dialogue similar to this
![Screenshot-20201018192956-504x278](https://user-images.githubusercontent.com/4218833/96377078-dad4e600-117a-11eb-8a21-9d04de59d435.png)
Hope this helps. Thanks

**Comment by romprod** [comment]
Brilliant, thanks
