### ISSUE TITLE
Set Device Temperature Offset

### ISSUE THREAD

**Issue by Robotrock983** [mattdavis90/node-red-contrib-tado-client#26]
I have a problem with the Tado Node.

I'm a noob but with this node I managed to automate the georeferentiation function of Tado, that for v3+ is no more free.

Now'm trying to set dinamically the Offset of the temperature of a Tado Thermostatic Valve.
I have a separate sensor that picks the correct temperature of the room, but I tried to inject in the Tado node this temperature or the delta T but nothing happens, the node continues to set the delta T to 0.
Must I create a node for every Delta T?

Sorry for the noob answer but I can't find documentation in internet of this fantastic node.

Best regards
Roberto

**Comment by mattdavis90** [comment]
Hi @robotrock983 thanks for getting in touch. It's great to have you using the library.

I don't own one of the thermostatic valves so I'm not 100% sure which API call you're using but from a Google it looks like it will be the setTemperarureOffset call. If that's the case then I think you'll want a function node to set the msg.temperatureOffset variable.

Hope that helps but happy to look into it more if it doesn't

**Comment by Robotrock983** [comment]
Thank you @mattdavis90 !!!

It works like a charm!
