### ISSUE TITLE
Error 403

### ISSUE THREAD

**Issue by britaliano** [mattdavis90/node-red-contrib-tado-client#28]
Hi, I have set up a very simple flow to check the connection but all I ever get in Debug is "Error: Request failed with status code 403".

API call is "Get the home info".

I have entered my details as per my Tado account.

The Home ID is the same as on my Tado account and the Name is just "Details".

Am I missing something?

**Comment by mattdavis90** [comment]
Hi, I have tried a number of times to replicate this and the only way that I can replicate it is if I miss-spell my username or password, or if I request a home ID that doesn't belong to me. Apologies that this isn't an answer. 403 is HTTP Forbidden which would also imply that your user credentials are incorrect for the home ID that you're requesting. Are you able to try "Get the current user" call? This will respond with an array of homes. Thanks

**Comment by britaliano** [comment]
Thanks Matt!

Changing to "Get the current user" does work and brings back the id of the Home, which is the same as that I am using in the config!

The name of my home is simply a name and has no strange characters. It does have a capital letter at the start, that's all.

**Comment by britaliano** [comment]
Ah! I used the numerical value for Home that was returned in the previous step.

So you had it spot on, I must have missed a step that showed how to get the required numerical home ID.

Thanks again.

**Comment by mattdavis90** [comment]
Hi britaliono, no problem and glad you got sorted. Maybe I need to adjust the home text on the page and suggest the steps you took. Sorry it took a week to get back to you. I'll close the ticket now 🙂
