### ISSUE TITLE
Temperature offset not in README.md

### ISSUE THREAD

**Issue by Davrosx** [mattdavis90/node-red-contrib-tado-client#30]
Having been trying to set the offset in nodered using values from msg.payload and in reading your README.md documentation I had been setting msg.temperature to the offset that I wanted as it was the only temperature related choice in the readme but couldn't get it working. 

Having reviewed your code I note you have a variable temperatureOffset which is not in the documented list. When I set the offset to msg.temperatureOffset it works as expected.

This is a suggestion to include this and any other variables in your README.md to assist future users.

**Comment by mattdavis90** [comment]
Hi Davrosx, thanks for the information. There have been a number of changes since I wrote the README so this doesn't surprise me. Apologies for the confusion. Are you able to open a pull request with the changes?
