### ISSUE TITLE
node-red config installation fatal error

### ISSUE THREAD

**Issue by RobertZwets** [mattdavis90/node-red-contrib-tado-client#34]
installation on node-red fails due to 

binding.cc:28:10: fatal error: zmq.h: No such file or directory 
See
[tado config error.txt](https://github.com/mattdavis90/node-red-contrib-tado-client/files/5984113/tado.config.error.txt)

**Comment by mattdavis90** [comment]
Hi @RobertZwets, do you have a bit more information about your installation? Node version? CPU architecture? Operating System? I've never seen this error before and I'm pretty sure there is no dependency for ZeroMQ in the codebase so I'm wondering if it could be another plugin, but happy to look into it if you could provide those details. Thanks

**Comment by RobertZwets** [comment]
Hi Matt.
Thanks for the kind willingness to have a look on this.
Node Red version : 1.2.6: Maintenance Release
Running in Docker on Synology NAS; OS Version 6.
List of palettes installed :
node-red 1.2.6
node-red-contrib-aedes 0.4.0
node-red-contrib-buienradar 0.4.1
node-red-contrib-heater-controller 2.0.2
node-red-contrib-image-tools 1.4.0
node-red-contrib-json 0.2.0
node-red-contrib-jsonpath 0.1.1
node-red-contrib-moment 4.0.0
node-red-contrib-mqtt-broker 0.2.5
node-red-contrib-persist 1.1.1
node-red-contrib-simpletime 2.10.0
node-red-contrib-tado-client 0.9.5
node-red-dashboard 2.27.0
node-red-node-openweathermap 0.3.2
node-red-node-rbe 0.2.9
node-red-node-tail 0.1.1
node-red-node-ui-iframe 0.1.2
node-red-node-ui-list 0.3.4
node-red-node-ui-table 0.3.10


See attachment of the node red log file during installation , which reports:
[info]  - node-red-contrib-tado-client:tado : SyntaxError: Invalid or unexpected token
[info]  - node-red-contrib-tado-client:tado-config : SyntaxError: Invalid or unexpected token
The docker node red log file:
 2021-02-15 20:44:39	stdout	15 Feb 20:44:39 - [info]  - tado
2021-02-15 20:44:39	stdout	15 Feb 20:44:39 - [info]  - tado-config
2021-02-15 20:44:39	stdout	15 Feb 20:44:39 - [info] Waiting for missing types to be registered: 
After installation one node is showing up. Creating a new Contrib profile is possible however the settings are not saved, after deployment they are lost again.
Deployment comes with error:
Flows stopped due to missing node types.
•	tado-config
•	tado
See 
node.jpg
empty config mode.jpg
palette warning.jpg
Hope this give you some insights.
Kind Regards
Robert

![empty config mode](https://user-images.githubusercontent.com/53395173/108114474-20f27580-7099-11eb-9cf0-bb5be1b76d68.jpg)
![node red docker log](https://user-images.githubusercontent.com/53395173/108114493-28b21a00-7099-11eb-9c61-503ec5663b78.jpg)
![node](https://user-images.githubusercontent.com/53395173/108114503-2e0f6480-7099-11eb-9508-8de30814fdf7.jpg)
![palette warning](https://user-images.githubusercontent.com/53395173/108114553-3c5d8080-7099-11eb-9861-67b7d0552ec7.jpg)
[nodred log tado.txt](https://github.com/mattdavis90/node-red-contrib-tado-client/files/5991344/nodred.log.tado.txt)

**Comment by mattdavis90** [comment]
Hi @robertzwets thanks for replying. Looking at the errors that you're getting I'm going to guess that you're running an older version of nodejs. The plugin requires at least version 12 of node to work, I believe there is a docker tag for a v12 image that should help you out. Let me know if you're still having issues. Thanks

**Comment by mattdavis90** [comment]
#27 may be of help

**Comment by RobertZwets** [comment]
Hi Matt,
Thank you very much! This was the case indeed. 
re install after upgrage has been succesfull. 
Although the Docker hub offered to install "the lastest" version, this seemed not to be the case at all.

**Comment by mattdavis90** [comment]
No problem. Glad that helped.
