### ISSUE TITLE
Feature Request: Tado Pollen status

### ISSUE THREAD

**Issue by derekoharrow** [mattdavis90/node-red-contrib-tado-client#35]
The Tado app has a Pollen status in it, providing today/tomorrow/next day pollen for Tree, Weed and Grass.
There is a v1 API call to get this, but that seems to be out of date compared to what's in the Tado app.
`https://acme.tado.com/v1/homes/XXX/airComfort?latitude=XXX1&longitude=XXXX&username=XXXXX&password=XXXXXXXXXXXXXXXXXX`
_(from https://community.home-assistant.io/t/pollen-again-but-for-the-uk/211480)_

I'm sure there must be a more up to date version of this API call that is correct and matches what's in the iPhone App. Is there any way to get hold of this info and include it?

I know there is the GetAirComfort option, and I'm guessing this would be something similar.

Thanks

**Comment by mattdavis90** [comment]
I've added the call into the underlying library and this commit adds the functionality here also. 0.9.6 will be released shortly with detailed air comfort support

**Comment by derekoharrow** [comment]
Wow! That was quick - thanks!

**Comment by derekoharrow** [comment]
Works great - thank you!

**Comment by mattdavis90** [comment]
No problem. Glad it is working for you
