### ISSUE TITLE
Feature request: Get temperature from Tado thermostat

### ISSUE THREAD

**Issue by spongioblast** [mattdavis90/node-red-contrib-tado-client#45]
Hi
Could you kindly tell me how to get the temperature of a Tado thermostat? Under devices I only see the option "Identify". Is this possible with a payload? If so, what would the payload be and how does the node need to be configured? Thanks!

**Comment by spongioblast** [comment]
It's possible to get it room the zone's state, that's good enough!

**Comment by mattdavis90** [comment]
Glad you got sorted. Apologies that it wasn't clear initially. If there's anything you think could be added to make it easier to use. Please let me know, thanks
