### ISSUE TITLE
config node not accessable

### ISSUE THREAD

**Issue by sparky-Ol** [mattdavis90/node-red-contrib-tado-client#46]
Hi,

when I add a tado-node I can't acces the config node:
![grafik](https://user-images.githubusercontent.com/50078350/193411502-6af7d36c-a5e9-4ce7-aae6-cdb9b1c13bd7.png)

In nodeoverview the confignode is in use:
![grafik](https://user-images.githubusercontent.com/50078350/193411551-47430b19-2c2c-4d06-a7c8-718d3a8f8256.png)

Any idea?

Sascha

**Comment by mattdavis90** [comment]
Hi Sascha,

Thanks for getting in touch. Do you know which version of NodeRed you are running. The `Home`, `_Path` and `Interval(s)` aren't the properties I'd expect to see on the Tado Node.

Thanks

**Comment by sparky-Ol** [comment]
Hi Matt
i use node red in a homatic environment:
A Raspi with [PiVCCU](https://github.com/alexreinert/piVCCU)
Node red is running as [RedMatic](https://github.com/rdmtc/RedMatic/tree/v7.2.1)-addon.
Current Version: 1.2.9: Maintenance Release

Thanks
Sascha

**Comment by mattdavis90** [comment]
Hi,

I've never used PiVCCU or RedMatic but I just started up a v1.2.9 Docker image and tried out the v0.9.8 plugin and it works ok. 

The node config gives the following properties.

![Screenshot-20221001200458-541x312](https://user-images.githubusercontent.com/4218833/193424561-c2436478-6fad-4d76-826f-ec9393d331c9.png)

I'm quite confused why it isn't giving you the correct properties. Could I ask what version of node.js you're running? The plugin requires at least v12 - this will probably appear in your NodeRed logs as something similar to

```
1 Oct 19:00:16 - [info] Waiting for missing types to be registered:
1 Oct 19:00:16 - [info]  - tado-config
1 Oct 19:00:16 - [info]  - tado
```

**Comment by sparky-Ol** [comment]
Hi Matt,
i made it working. I don't know why, but i think there was some stuff left from the other tado node (without client).  
I did a cleanup, a reboot and a reinstallation an d noeit woks.

Thanks
Sascha

**Comment by mattdavis90** [comment]
Great to hear. Not a problem.
