### ISSUE TITLE
terminationType Auto doesn't work

### ISSUE THREAD

**Issue by janves** [mattdavis90/node-red-contrib-tado-client#48]
Hi,

first of all thank you for the great work you did here! I really like the project.
Let's talk about my Problem: I am trying to use a window contact sensor to control the tado thermostat. When somebody opens the window it should turn the thermostat off and when it gets closed again the terminationType should be auto. Sadly the part where it sets the thermostat to open again doesn't work for me. I use the following function as input for your node: 

```
if(msg.payload.ContactSensorState){
    msg.topic = "setZoneOverlay"
    msg.apiCall = "setZoneOverlay"
    msg.homeid = "homeid"
    msg.zoneId = "10"
    msg.power = "OFF"
}else{
    msg.topic = "setZoneOverlay"
    msg.apiCall = "setZoneOverlay"
    msg.homeid = "homeid"
    msg.zoneId = "10"
    msg.deviceid = "7"
    msg.terminationType = "auto"
}


return msg;
```
Instead of turning the device to the schedule, it just sets the target temperature to 18 degrees.
Is this a bug or am I doing something wrong?
Thanks a lot for your help already!

**Comment by mattdavis90** [comment]
Hi,

I'm glad the library is helping you out.

I tested out your code snippet and noticed that your `homeid` has a lower-case `i`, this should be `homeId` although this doesn't appear to actually affect your issue.

Testing out the API calls on the Tado web app it looks as though Tado have switched from using the `setOverlay` call to using the `deleteOverlay` call for clearing overlays. If you tweak your code to something like

```javascript
if(msg.payload.ContactSensorState){
    msg.apiCall = "setZoneOverlay"
    msg.homeId = 12345
    msg.zoneId = 1
    msg.power = "off"
}else{
    msg.apiCall = "clearZoneOverlay"
    msg.homeId = 12345
    msg.zoneId = 1
}

return msg;
```

Does that work as expected? Thanks

**Comment by janves** [comment]
It seems to work now, thanks a lot!

**Comment by Brewj** [comment]
Matt just a massive thank you for your development with this, top work sir thank you!

**Comment by mattdavis90** [comment]
You're very welcome
