### ISSUE TITLE
'Set a device temperature offset' seems to clear Zone overlay to

### ISSUE THREAD

**Issue by ThePhiMuc** [mattdavis90/node-red-contrib-tado-client#50]
HI! 

I'm using 'set device temperature offset' (I'm on v.010.1) several times a day for any of my rooms to sync Tado with external temperature sensors.
Whenever a room is updated with a new offset it switches back to the regular timetable afterwards and ignores formally done manual temperature-changes.

Example:
The timetable for a room says "18 degrees"
I manually change the temperature to 20 degrees (within the app or at the termostate itself)
Some minutes later Node Red sends a 'set temperature offset' for the room
Tado switches to 18 degress again - but should stay at 20 degrees.

If been testing with the room settings "manual change stays until endes by user" and "until next autmatic change" - this doesn't seem to have any effect - it's always back to the timetable as soon the offset was updated.

This does not happen if I change the offset within the (App/Web) Tado settings (temparature stays at 20 degrees after setting a new offset manually) so I assume it's a 'problem' with the tado client.

Sure - I could change my node-red-routines to read the current target-temperature before updating an offset and set the temperature to that value after the update - but it would be much more easy if the client woudn't force Tado to switch back to the timetable ;-)

I would be glad if you could investigate this.
Thanks,
Philipp

**Comment by mattdavis90** [comment]
Hi @ThePhiMuc ,

Thanks for using the library and getting in touch. I don't think I have a device that's capable of changing the offset to test this. If you're able to log in to my.tado.com in Chrome or Firefox then using the network tab in the inspector should show you what API calls the web client is using. This is the technique that I've used to reverse engineer the rest of the library.

Alternatively, I have some of the Tado TRVs on order which I do think accept the set offset so in a couple weeks I may be able to test this at home.

Thanks

**Comment by ThePhiMuc** [comment]
Wow, thanks for that fast response!

I took a look at the Dev-Tools. The json is exactly the same as your Plugin is generating, eg:
{"celsius":-0.60,"fahrenheit":-1.08}
Endpoint is https://my.tado.com/api/v2/devices/VAXXXXX/temperatureOffset?ngsw-bypass=true

Now I would have to investigate the communication NodeRed ist doing towards Tado.
I'm not a Node Red expert, so:
Is there a way to see, wich requests and responses are transmitted? 
The default Node Red shell (the Linux terminal which is shown if you start NodeRed manually instead of an automated service) doesn't include that kind of data.

I just did another test while checking the DevTools:
No change at the (manualle set) target-temperature.
In Node Red I used an inject-node with the Tado Client to modify the offset for the same room I investigated within the Webapp before: It's back to the timetable afterwards.
So there must be a difference somewhere. Let's find out ;-)

And, yes: if you ceceive your TRVs you would be able to set the offset.
The TVR is located in a room and a room can have an offset.
Due to the fact that the thermostate measures the temperature directly at the thermostate itself instead of somewhere in the room, there can be massive offsets (up to 4 degrees in my case)...

CU,
Philipp

**Comment by mattdavis90** [comment]
No problem.

That's interesting. Do you see any other API calls at the same time? Such as setting the overlay at the same time? I searched the previous issues related to offset and couldn't find mention of this happening previously.

I'm not 100% sure how to do that through NodeRed (maybe I should add a debug option into the node?) but the underlying library that this plugin uses is written in JavaScript/Typescript if you're familiar with the language then that may be easier to debug exactly what calls and responses you're getting.

I was aware of the discrepancy between the TRV and the room temperature so was imagining have to create something like what you're talking about. I was thinking to use an ESP32 with a temperature sensor feeding to NodeRed to adjust the offset also. So I'm invested in this working not only for the project 🙂

**Comment by ThePhiMuc** [comment]
I didn't recognize any other call - but I'm only talking about the webapp.

Actually I'm figuring out how to sniff the node red traffic (so, yes: a debug-option would be a great idea even it would not be used very often). 
I haven't found a fast solution here (or didn't use google right). Seems that the Node Red logs don't include the requests/responses which are sent from the nodes. 
Currently I'm thinking about sniffing the network traffic with Wireshark (this will be a lot of work, I'm using it very seldom and always forget everything about it and have to start from scratch).

I'll let you know as soon I got some more information (might take a few days)

**Comment by mattdavis90** [comment]
If it helps, this is the flow that I'm using to test. You'll need to change you're `home_id` and `zone_id` in each Tado node but hopefully it helps.

```json
[
    {
        "id": "f88af7a282239296",
        "type": "tab",
        "label": "Flow 1",
        "disabled": false,
        "info": "",
        "env": []
    },
    {
        "id": "a00724e6d567809c",
        "type": "inject",
        "z": "f88af7a282239296",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 140,
        "y": 200,
        "wires": [
            [
                "abebeb8603a88cec"
            ]
        ]
    },
    {
        "id": "abebeb8603a88cec",
        "type": "tado",
        "z": "f88af7a282239296",
        "configName": "d1cf260f.0bb368",
        "apiCall": "getZoneOverlay",
        "homeId": "123",
        "deviceId": "",
        "zoneId": "3",
        "power": "on",
        "temperature": "18",
        "terminationType": "manual",
        "terminationTimeout": 900,
        "fanSpeed": "AUTO",
        "acMode": "AUTO",
        "name": "Get Overlay",
        "reportDate": "",
        "presence": "HOME",
        "geoTracking": true,
        "temperatureOffset": 0,
        "windowDetection": true,
        "windowDetectionTimeout": 900,
        "openWindowMode": true,
        "timetableId": "",
        "x": 330,
        "y": 200,
        "wires": [
            [
                "17d6bf8bf5ac0d5b"
            ]
        ]
    },
    {
        "id": "99b7fef281faedb2",
        "type": "inject",
        "z": "f88af7a282239296",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 140,
        "y": 280,
        "wires": [
            [
                "77aae9b041c3f018"
            ]
        ]
    },
    {
        "id": "77aae9b041c3f018",
        "type": "tado",
        "z": "f88af7a282239296",
        "configName": "d1cf260f.0bb368",
        "apiCall": "setZoneOverlay",
        "homeId": "123",
        "deviceId": "",
        "zoneId": "3",
        "power": "on",
        "temperature": "5",
        "terminationType": "manual",
        "terminationTimeout": 900,
        "fanSpeed": "AUTO",
        "acMode": "AUTO",
        "name": "Heating On",
        "reportDate": "",
        "presence": "HOME",
        "geoTracking": true,
        "temperatureOffset": 0,
        "windowDetection": true,
        "windowDetectionTimeout": 900,
        "openWindowMode": true,
        "timetableId": "",
        "x": 330,
        "y": 280,
        "wires": [
            [
                "17d6bf8bf5ac0d5b"
            ]
        ]
    },
    {
        "id": "36510e8eb666fd48",
        "type": "inject",
        "z": "f88af7a282239296",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 140,
        "y": 360,
        "wires": [
            [
                "b60c8324a5edf8c4"
            ]
        ]
    },
    {
        "id": "b60c8324a5edf8c4",
        "type": "tado",
        "z": "f88af7a282239296",
        "configName": "d1cf260f.0bb368",
        "apiCall": "clearZoneOverlay",
        "homeId": "123",
        "deviceId": "",
        "zoneId": "3",
        "power": "on",
        "temperature": "18",
        "terminationType": "manual",
        "terminationTimeout": 900,
        "fanSpeed": "AUTO",
        "acMode": "AUTO",
        "name": "Clear Overlay",
        "reportDate": "",
        "presence": "HOME",
        "geoTracking": true,
        "temperatureOffset": 0,
        "windowDetection": true,
        "windowDetectionTimeout": 900,
        "openWindowMode": true,
        "timetableId": "",
        "x": 340,
        "y": 360,
        "wires": [
            [
                "17d6bf8bf5ac0d5b"
            ]
        ]
    },
    {
        "id": "3e5c8ffd9778f820",
        "type": "inject",
        "z": "f88af7a282239296",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 140,
        "y": 120,
        "wires": [
            [
                "9adea8ea53476251"
            ]
        ]
    },
    {
        "id": "17d6bf8bf5ac0d5b",
        "type": "debug",
        "z": "f88af7a282239296",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "payload",
        "targetType": "msg",
        "statusVal": "",
        "statusType": "auto",
        "x": 590,
        "y": 240,
        "wires": []
    },
    {
        "id": "9adea8ea53476251",
        "type": "tado",
        "z": "f88af7a282239296",
        "configName": "d1cf260f.0bb368",
        "apiCall": "setDeviceTemperatureOffset",
        "homeId": "123",
        "deviceId": "VA3",
        "zoneId": "3",
        "power": "on",
        "temperature": "18",
        "terminationType": "manual",
        "terminationTimeout": 900,
        "fanSpeed": "AUTO",
        "acMode": "AUTO",
        "name": "Set Device Offset",
        "reportDate": "",
        "presence": "HOME",
        "geoTracking": true,
        "temperatureOffset": "0.3",
        "windowDetection": true,
        "windowDetectionTimeout": 900,
        "openWindowMode": true,
        "timetableId": "",
        "x": 350,
        "y": 120,
        "wires": [
            [
                "17d6bf8bf5ac0d5b"
            ]
        ]
    },
    {
        "id": "d1cf260f.0bb368",
        "type": "tado-config",
        "name": ""
    }
]
```

**Comment by ThePhiMuc** [comment]
<tldr> 'Set overlay' is working fine - another one of my flows has a problem </tldr>

After setting tons of debug messages I found out, that "set device overlay" is working as expected and DOESN'T remove a overlay.
I've got another flow runnig, wich turns heating off/on if window sensors send an open/close event. After receiving a "closed" event I'm polling l a virtual hombridge switch (I built ONE virtual global heating on/off switch 'cause I'm using two different Tado systems). If a window is closed and the main switch is "on", I'll switch tado to "auto".
Found out, that polling the homebrindge status seems to be wrong - this node transmits the status every once and a while even if NOT queried by my flow. THIS ist the reason why the overlay is deleted. 

SO: please apologize I thought your node has got a bug. Seems to be another node ;-)
And athank's a lot for investigating this!

Have a wonderful Christmas!
Philipp

**Comment by mattdavis90** [comment]
Hi Philipp, no problem at all. I'm glad you got to the bottom of the issue. Have a great Christmas as well.
