### ISSUE TITLE
clearZoneOverlays

### ISSUE THREAD

**Issue by AleksCee** [mattdavis90/node-red-contrib-tado-client#56]
I have create a flow to reset all zones to the default.

<img width="738" alt="grafik" src="https://github.com/mattdavis90/node-red-contrib-tado-client/assets/2960655/1f6088ef-3608-4054-bcc0-bf7d51812444">

Split only make a call for every zone and the change node moves the payload.id to msg.zoneId as a string.

After testing I found this in the nodeRED log:

"This method of clearing zone overlays will soon be deprecated, please use clearZoneOverlays"

Is the API out of date?

Thanks, Alex

**Comment by mattdavis90** [comment]
Hi,

Short version: you're safe to ignore it.

The method call that is exposed in NodeRed is only for a single zone. The Tado API and the underlying library that this node uses both have functionality to set multiple zones. I haven't finished implementing this in the NodeRed library and I haven't fully worked out all the quirks of the newer API (though my reverse engineering of it seems stable so far). There are issues tracking this already. #39 for the original multi-zone function and #44 for adding the NodeRed UI elements but I hit a time blocker implementing it how I'd like.
