### ISSUE TITLE
dynamic "set zone overlay"

### ISSUE THREAD

**Issue by drozel** [mattdavis90/node-red-contrib-tado-client#6]
Hi, firstly thanks for the great work, it is very helpful!
I have an issue, which don't let me configure the custom scenarios:
function "set a zone overlay" is only able to take parameters from input form, so, statically, but sometimes it can be needed, to pass them via JSON obect dynamically.
For example, it is impossible, to save the current overlay to a variable, clear it, and then restore the previous values again.

Hopefully i could properly explain my idea

**Comment by mattdavis90** [comment]
Hi, thanks for the interest in my library. You should be able to send a message into the node that contains an object that looks like
```
{
temperature: 16,
terminationType: "timer",
terminationTimeout: 60
}
```
This would then set the temperature to 16C for the next hour. The library should allow you to override any property dynamically by setting that property in the incoming message. If this doesn't work let me know. There may be an error somewhere. Thanks

**Comment by drozel** [comment]
@mattdavis90 it seems not working..
I have following message:
![Screenshot from 2019-08-26 21-06-42](https://user-images.githubusercontent.com/6229397/63716228-c7afda00-c845-11e9-8c25-3e6ce6050520.png)

on the input of the node:
![Screenshot from 2019-08-26 21-07-24](https://user-images.githubusercontent.com/6229397/63716269-d8f8e680-c845-11e9-9694-273dd9e10c20.png)

and it sets the values from the form, not from message

**Comment by mattdavis90** [comment]
Hi,

Can I ask which version of NodeRed and the plugin you are using?

I have just tried this on my own installation and find it to be working as expected. I used the following flow.

```
[
    {
        "id": "a7bf1826.eacc38",
        "type": "tab",
        "label": "Flow 2",
        "disabled": false,
        "info": ""
    },
    {
        "id": "271d7836.57a988",
        "type": "debug",
        "z": "a7bf1826.eacc38",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "x": 770,
        "y": 380,
        "wires": []
    },
    {
        "id": "5526bbab.b41104",
        "type": "inject",
        "z": "a7bf1826.eacc38",
        "name": "",
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "x": 120,
        "y": 320,
        "wires": [
            [
                "c89fdf86.2ea3f"
            ]
        ]
    },
    {
        "id": "68b57035.b45fd",
        "type": "tado",
        "z": "a7bf1826.eacc38",
        "configName": "d1cf260f.0bb368",
        "apiCall": "clearZoneOverlay",
        "homeId": "",
        "deviceId": "",
        "zoneId": "",
        "power": "on",
        "temperature": "18",
        "terminationType": "manual",
        "terminationTimeout": 900,
        "name": "",
        "x": 500,
        "y": 300,
        "wires": [
            [
                "271d7836.57a988"
            ]
        ]
    },
    {
        "id": "c89fdf86.2ea3f",
        "type": "function",
        "z": "a7bf1826.eacc38",
        "name": "",
        "func": "msg.apiCall = \"setZoneOverlay\";\nmsg.homeId = 12345;\nmsg.zoneId = 1;\nmsg.terminationType = 'MANUAL';\nmsg.temperature = 15;\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "x": 360,
        "y": 340,
        "wires": [
            [
                "68b57035.b45fd",
                "271d7836.57a988"
            ]
        ]
    },
    {
        "id": "d1cf260f.0bb368",
        "type": "tado-config",
        "z": "",
        "name": ""
    }
]
```

**Comment by drozel** [comment]
@mattdavis90 ah, the API call name was ,issin

**Comment by mattdavis90** [comment]
I can't remember whether terminationTimeout is in seconds or minutes to be honest. I'd guess minutes but could be wrong. It is definitely not an absolute timestamp though. Thanks for testing this functionality, I haven't really exercised all the functions. I only really use a small set of the features.

**Comment by drozel** [comment]
@mattdavis90 no, it seems not working.. I taking the seconds the same way as in the form (for example:
`msg.apiCall = "setZoneOverlay";
msg.homeId = 12345;
msg.zoneId = 1;
msg.terminationType = 'TIMER';
msg.terminationTimeout = 900;
msg.temperature = 15;
msg.payload = false;
return msg;`

and result message (on the output of TADO block) getting "MANUAL" type of the termination...

**Comment by mattdavis90** [comment]
Could you try
```
msg.terminationType = 'timer';
```
I think the issue is that the code is doing a case sensitive match on that string so ignoring the terminationTimeout parameter. I'm away from home at the minute but when I'll back I'll fix that bug.

**Comment by drozel** [comment]
@mattdavis90 
yep! It works. Have i to make it back to "TIMER" when you fix it or will it work in both cases?

**Comment by mattdavis90** [comment]
I'll make sure that it makes for both TIMER and timer, and also TiMer for that matter. It should be an insensitive match.

Regarding the parameters; terminationType dictates whether terminationTimeout is used or not. Timeout is not used if type is set to either manual or auto. Both can also be set in the form and optionally overiden by message properties. I think I've covered all possible use cases but may well be wrong.

**Comment by drozel** [comment]
@mattdavis90 yeah, it sounds good!
I meant only, that it makes no sense to jump into timeout mode if terminationMode = 'MANUAL' and the terminationTimeout is accidentally set to smth, because i would select the behavior via direct properties without some deduction from other fields.

Thank you! It is very helpful, i can disable the heating now if my window is opened and then restore it back after it is closed   ٩( ᐛ )و

**Comment by mattdavis90** [comment]
That's a good point. I'll double check the logic as I correct the above bug. Thanks

Glad it is working now
