### ISSUE TITLE
This method of setting zone overlays will soon be deprecated, please use setZoneOverlays

### ISSUE THREAD

**Issue by Jleagle** [mattdavis90/node-red-contrib-tado-client#61]
Hi, i am getting `This method of setting zone overlays will soon be deprecated, please use setZoneOverlays` in the logs when i call 'Set a Zone\'s overlay'

https://i.imgur.com/TIDc6uJ.png

Seems like it should already be being called.

Thanks.

**Comment by Jleagle** [comment]
I resaved a node and it started giving this error:

https://i.imgur.com/QOJoVJh.png

**Comment by mattdavis90** [comment]
Hi,

I can't see either of your images. You should be able to upload directly into the comment box on GitHub and don't need to use a 3rd party host.

The message is only a warning. I fully intended to migrate this client over to using the newer API call but haven't found time. It is fully safe to ignore.

Is this causing you any problems other than the log message?

**Comment by mattdavis90** [comment]
To clarify, the warning comes from the underlying node library (which I also author) and not from Tado themselves. The singular API in the underlying library isn't really being updated anymore and I didn't want to duplicate the business logic between the singular and plural calls so chose to deprecate the singular ones. Implementing the UI elements in NodeRed to enable multiple zone overrides became very time consuming and complicated.

**Comment by Jleagle** [comment]
Not causing issues other than in the logs, sounds fine, cheers!

**Comment by mattdavis90** [comment]
Ok. In that case I'll close the issue. Apologies for any inconvenience caused. Thanks

**Comment by Jleagle** [comment]
> I resaved a node and it started giving this error:
> 
> https://i.imgur.com/QOJoVJh.png

Hi, i forgot about the above issue, re-uploaded the images so you can see them. If you like i can create a seperate issue.

After updating to the latest version, the nodes seemed okay at first but after going into them and saving the node, i get this error.

![QOJoVJh_d](https://github.com/mattdavis90/node-red-contrib-tado-client/assets/381099/61f113ce-6ec0-4ed3-8e94-d65ba1c0509c)

![TIDc6uJ_d](https://github.com/mattdavis90/node-red-contrib-tado-client/assets/381099/0f5128bd-54fe-43b9-a43d-89581d0c9f3a)

**Comment by mattdavis90** [comment]
Hi,
Sorry, I didn't realise there were two issues.
I think I've seen that before. There was a bug in one of the releases that didn't quite clear out any default values correctly. I think updating to the latest release should work. If it doesn't then let me know and I'll do some more digging. Alternatively, you can edit the node, temporarily pick a call that displays the Tariff box, type a 0 in it, then switch everything back to the way you had it before, then save. Hopefully updating fixes it though and you don't have to do that faff for each node. NodeRed doesn't have a nice built-in way for nodes to upgrade their internal config.

**Comment by Jleagle** [comment]
> Alternatively, you can edit the node, temporarily pick a call that displays the Tariff box, type a 0 in it, then switch everything back to the way you had it before, then save.

This fixed it, thanks. This happened using the latest version.

**Comment by mattdavis90** [comment]
Glad it's fixed. I'll double check the released version and how I'm handling the config migrations. I'll leave this open to track. Thanks
