### ISSUE TITLE
Palette stopped working on jan 4th

### ISSUE THREAD

**Issue by fmarzocca** [mattdavis90/node-red-contrib-tado-client#62]
Hi,

this palette stopped working yesterday. I can't even login to my account. Credentials are expired...

**Comment by mattdavis90** [comment]
Hi,

Did this stop in December or January? December 4th wasn't yesterday.

Can you please check that you can log in to https://my.tado.com

Thanks

**Comment by fmarzocca** [comment]
Sorry for the date, I have edited the title.
No, I can't log in. It say wrong credentials, but of course I have triple.checked that I was entering my usual credentials.

**Comment by mattdavis90** [comment]
I see. If you can't log in to the official Tado site then this isn't an issue with this library I'm afraid and will have to be taken up with Tado either by performing a password reset or raising a support ticket. Sorry I can't really help, this is an unofficial library

**Comment by fmarzocca** [comment]
You're more than right. Sorry.
