### ISSUE TITLE
UPDATE README. Make it easier for Novice Users

### ISSUE THREAD

**Issue by MankiniChykan** [mattdavis90/node-red-contrib-tado-client#65]
I tried this node a few years back and only just got it going today. I will admit I have gained a fair bit more experience now than I had two years ago but your instructions are not clear for a novice.

If you could update your README on Node Red and Git Hub that would make it much clearer on how to setup this node for the novice.

Possibly adding a picture of the nodes required.

EXAMPLE: (From your comment in your example - it was not until I downloaded this example flow I got it working)

**You will need to configure a `tado_config` node with your Tado Username and Password before using the examples

You should also replace the `home_id` in the calls with your `home_id` which can be found using the first example of `getMe` API call.

You can read your 'home_id' in the debug window.**

![Slide1](https://github.com/mattdavis90/node-red-contrib-tado-client/assets/101962955/6bbc51c7-bf19-414c-b68a-06bf331d6eaa)
![Slide2](https://github.com/mattdavis90/node-red-contrib-tado-client/assets/101962955/ffec8b6b-5181-4621-aee1-3ddcaae0e704)

**Comment by mattdavis90** [comment]
Hi, firstly apologies that it has taken me so long to reply. Also, apologies that you had a bumpy start to using the node. The documentation was written many years before I realised the popularity of the node and was mostly in-line with the nodered documentation at time of writing. I've pushed changes to master that hopefully address your concerns. Thanks

**Comment by MankiniChykan** [comment]
No problems,

Thanks for the great work

---
Andrew (Chicken) Hunter
0417525998

On 2024-05-31 05:59, Matt Davis wrote:

> Hi, firstly apologies that it has taken me so long to reply. Also, 
> apologies that you had a bumpy start to using the node. The 
> documentation was written many years before I realised the popularity 
> of the node and was mostly in-line with the nodered documentation at 
> time of writing. I've pushed changes to master that hopefully address 
> your concerns. Thanks
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>


Links:
------
[1] 
https://github.com/mattdavis90/node-red-contrib-tado-client/issues/65#issuecomment-2140773673
[2]

**Comment by MankiniChykan** [comment]
I have found, as I have climbed the steep learning curve of 
homeassistant and node red, I am able to go back and get things going 
that I could not when I started.

One thing I have noticed is absolute noobs really do need some of the 
step by step stuff that we neglect to mention at times.

---
Andrew (Chicken) Hunter
0417525998

On 2024-05-31 05:59, Matt Davis wrote:

> Hi, firstly apologies that it has taken me so long to reply. Also, 
> apologies that you had a bumpy start to using the node. The 
> documentation was written many years before I realised the popularity 
> of the node and was mostly in-line with the nodered documentation at 
> time of writing. I've pushed changes to master that hopefully address 
> your concerns. Thanks
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>


Links:
------
[1] 
https://github.com/mattdavis90/node-red-contrib-tado-client/issues/65#issuecomment-2140773673
[2]

**Comment by mattdavis90** [comment]
Hi, yes it is totally easy to overlook this sort of thing. If you're content with the changes I've made then I'll close the issue. Thanks

**Comment by MankiniChykan** [comment]
Certainly, just make sure there is some screen snapshots.

---
Andrew (Chicken) Hunter
0417525998

On 2024-05-31 22:03, Matt Davis wrote:

> Hi, yes it is totally easy to overlook this sort of thing. If you're 
> content with the changes I've made then I'll close the issue. Thanks
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>


Links:
------
[1] 
https://github.com/mattdavis90/node-red-contrib-tado-client/issues/65#issuecomment-2141912150
[2]

**Comment by mattdavis90** [comment]
I'm slightly reluctant to add screenshots because they could get out of date then that's on me to keep updating them. Instead I've made sure to link to the official documentation where appropriate in my README. I've updated the installation section and added a Getting Started section that references both the example file and also the official docs on importing flows. Hopefully this works for you. Thansk

**Comment by MankiniChykan** [comment]
No problems

---
Andrew (Chicken) Hunter
0417525998

On 2024-06-03 07:52, Matt Davis wrote:

> I'm slightly reluctant to add screenshots because they could get out of 
> date then that's on me to keep updating them. Instead I've made sure to 
> link to the official documentation where appropriate in my README. I've 
> updated the installation section and added a Getting Started section 
> that references both the example file and also the official docs on 
> importing flows. Hopefully this works for you. Thanks
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>


Links:
------
[1] 
https://github.com/mattdavis90/node-red-contrib-tado-client/issues/65#issuecomment-2144032942
[2]
