### ISSUE TITLE
Payload or variable in Set overlay and Add meterreading

### ISSUE THREAD

**Issue by chrisda1969** [mattdavis90/node-red-contrib-tado-client#67]
Hi
I seem to be missing the option to set a variable or msg.payload to e.i temperature in the Set a zone overlay, and inthe function add energy meter reading. 
Will that be a available in the future?
I am using it in Home assistant Node red integration.
Thanks
Christian

**Comment by mattdavis90** [comment]
Hi Christian,

I'm sure I fully understand the question. The node will respond with details of a zone overlay as a JSON payload in `msg.payload`. You're also able to set properties going into the node, as documented, these are not `msg.payload` but `msg.temperature` for instance. This is a legacy thing and I don't wish to break working configurations.

I'm not sure if that answers your question or helps.

Thanks

**Comment by chrisda1969** [comment]
Hi Matt
Sorry, I didn't know that it was working like this. This gives me the posiblety to change the temperature.

Thanks

**Comment by mattdavis90** [comment]
No problem
