### ISSUE TITLE
TADO AC / Swing "OFF" gives "not allowed" error

### ISSUE THREAD

**Issue by RedOctoberSUI** [mattdavis90/node-red-contrib-tado-client#71]
Hi

First of all thank you very much for the great integration. Really the only way i can use Tado - as out of the box the AC Controller doesnt really work for us. Thanks again!

Im not sure if this is a bug or i am to daft to set correctly:

When i set to heat i set Swings to "OFF"
![image](https://github.com/user-attachments/assets/42f626de-bd22-4f8d-a1eb-cee53302c2b7)

However i then get an error that swings are not allowed.
![image](https://github.com/user-attachments/assets/9bb686bf-f07f-4beb-aa57-0517d7423627)

I would have expected that Swing "OFF" solves the problem, but it does not :)

Thanks!!

**Comment by mattdavis90** [comment]
Hi,

I'm glad the node is helpful for you.

Can you confirm which version of the node you're using? I'm pretty certain this has been raised before and I had hoped it had been fixed.

If you can log in to https://app.tado.com and create an overlay in the web app that does what you want then it should be replicable here. If you can get this working and you're comfortable using Chrome (or Firefox) DevTools then it would be great to see what API calls are being made by the app, particularly what is being send as the payload for the call to `/overlay`

Thanks

**Comment by mattdavis90** [comment]
Oh wow, I've never seen the overlay for an AC before - you get a lot of options.

Thanks for giving it a go. In Devtools if you open the "Network" tab, then set up the overlay you should see something like the following.

![Screenshot From 2024-11-26 20-06-51](https://github.com/user-attachments/assets/f7f3d032-be72-44e4-92d2-833feb902dad)

If you can click on the call to `overlay` then find the data in the `payload` tab, that's pretty much what I'm after. That should help work out what the Tado API is expecting. Thanks

**Comment by RedOctoberSUI** [comment]
Much appreciated directions!
![image](https://github.com/user-attachments/assets/bcb006c1-c1e2-4e3f-9828-c3435d3ce01d)


Seems much aligned with your settings - except for the horizontal swing. seems it really doesnt like that one :)

**Comment by mattdavis90** [comment]
Oh, interesting. You don't have a `horizontalSwing` at all. Ok. I'll see if I can work out some logic to auto remove that field

**Comment by RedOctoberSUI** [comment]
> Oh, interesting. You don't have a `horizontalSwing` at all. Ok. I'll see if I can work out some logic to auto remove that field

much appreciated!

**Comment by mattdavis90** [comment]
I've push v0.11.1 to npm - sometimes it can take NodeRed a little time to pick it up

**Comment by mattdavis90** [comment]
The new version calls `getZoneCapabilities` and checks whether `horizontalSwing` or `verticalSwing` is present in the `FAN` or `AUTO` mode before setting either property - hopefully that works for you

**Comment by RedOctoberSUI** [comment]
Works like a charm.. thank you so much!

**Comment by mattdavis90** [comment]
Woop woop 🥳

No problem, glad to help!
