### ISSUE TITLE
"Error: Client request error: getaddrinfo EAI_AGAIN auth.tado.com auth.tado.com:443"

### ISSUE THREAD

**Issue by alexpelli** [mattdavis90/node-red-contrib-tado-client#8]
Hi.. since the last update of today the node is instable and I receive the following message
"Error: Client request error: getaddrinfo EAI_AGAIN auth.tado.com auth.tado.com:443"
Do you have any suggestion?
Thank you

**Comment by mattdavis90** [comment]
Hi Alex,

Thanks for getting in touch. I'm not seeing this on my installation. I even tried a clean install to double check. EAI_AGAIN implies a DNS timeout so it may be that during the period you checked there was a DNS issue causing you to be unable to resolve auth.tado.com. If this persists though please let me know. I'll leave this issue open for a while.

Thanks

**Comment by alexpelli** [comment]
Hi Matt... thank you very much for your kind reply. It seems now it works regularly. I will back to you in case of any news.
Regards
